CREATE TABLE CATEGORIA (
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE TEXT
);

CREATE TABLE PRODUCTO (
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE TEXT,
MARCA TEXT,
CATEGORIA_ID TEXT,
PRECIO_UNITARIO FLOAT
);

CREATE TABLE SUCURSAL  (
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE TEXT,
DIRECCION TEXT
);

CREATE TABLE STOCK  (
ID INTEGER PRIMARY KEY NOT NULL,
SUCURSAL_ID TEXT,
PRODUCTO_ID TEXT,
CANTIDAD INT,
UNIQUE (SUCURSAL_ID, PRODUCTO_ID)
);

CREATE TABLE CLIENTE  (
ID INTEGER PRIMARY KEY NOT NULL,
NOMBRE TEXT,
TELEFONO INT
);

CREATE TABLE ORDEN (
ID INTEGER PRIMARY KEY NOT NULL,
CLIENTE_ID INTEGER,
SUCURSAL_ID INTEGER,
FECHA DATE,
TOTAL FLOAT
);

CREATE TABLE ITEM (
ID INTEGER PRIMARY KEY NOT NULL,
ORDEN_ID INTEGER,
PRODUCTO_ID INTEGER,
CANTIDAD INT,
MONTO_VENTA FLOAT
);


